//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
//
// This source code was updated by David Dossot (renamed classes to prevent collisions with existing ones)
// 
namespace NxBRE.InferenceEngine.Registry {
  using System.Xml.Serialization;
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class FileRegistryConfiguration {
      
    private EngineConfiguration[] engineField;
    
    private string folderField;
    
    private int fileLockedPonderatingTimeField;
    
    public FileRegistryConfiguration() {
        this.fileLockedPonderatingTimeField = 500;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Engine")]
    public EngineConfiguration[] Engines {
        get {
            return this.engineField;
        }
        set {
            this.engineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="folder")]
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="fileLockedPonderatingTime", DataType="int")]
    [System.ComponentModel.DefaultValueAttribute(500)]
    public int FileLockedPonderatingTime {
        get {
            return this.fileLockedPonderatingTimeField;
        }
        set {
            this.fileLockedPonderatingTimeField = value;
        }
    }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(ElementName="Engine", Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class EngineConfiguration {
      
      private RulesConfiguration rulesField;
      
      private object binderField;
      
      private string idField;
      
      /// <remarks/>
      public RulesConfiguration Rules {
          get {
              return this.rulesField;
          }
          set {
              this.rulesField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("CSharpBinder", typeof(CSharpBinderConfiguration))]
      [System.Xml.Serialization.XmlElementAttribute("VisualBasicBinder", typeof(VisualBasicBinderConfiguration))]
      [System.Xml.Serialization.XmlElementAttribute("FlowEngineBinder", typeof(FlowEngineBinderConfiguration))]
      public object Binder {
          get {
              return this.binderField;
          }
          set {
              this.binderField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="id", DataType="ID")]
      public string Id {
          get {
              return this.idField;
          }
          set {
              this.idField = value;
          }
      }
  }
    
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(ElementName="Rules", Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class RulesConfiguration {
      
      private string fileField;
      
      private RulesFormat formatField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="file")]
      public string File {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="format")]
      public RulesFormat Format {
          get {
              return this.formatField;
          }
          set {
              this.formatField = value;
          }
      }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  public enum RulesFormat {
      
      /// <remarks/>
      HRF086,
      
      /// <remarks/>
      RuleML08Datalog,
      
      /// <remarks/>
      RuleML086Datalog,
      
      /// <remarks/>
      RuleML086NafDatalog,
      
      /// <remarks/>
      RuleML09NafDatalog,
      
      /// <remarks/>
      Visio2003,
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(ElementName="CSharpBinder", Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class CSharpBinderConfiguration {
      
      private string fileField;
      
      private string classField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="file")]
      public string File {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
      public string Class {
          get {
              return this.classField;
          }
          set {
              this.classField = value;
          }
      }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(ElementName="VisualBasicBinder", Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class VisualBasicBinderConfiguration {
      
      private string fileField;
      
      private string classField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="file")]
      public string File {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="class")]
      public string Class {
          get {
              return this.classField;
          }
          set {
              this.classField = value;
          }
      }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(ElementName="FlowEngineBinder", Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class FlowEngineBinderConfiguration {
      
      private string fileField;
      
      private NxBRE.InferenceEngine.IO.BindingTypes typeField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="file")]
      public string File {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="type")]
      public NxBRE.InferenceEngine.IO.BindingTypes Type {
          get {
              return this.typeField;
          }
          set {
              this.typeField = value;
          }
      }
  }
  
}
