namespace org.nxbre.ri.drivers {
	using System.Reflection;
	using System.Xml;
	using System.Xml.Xsl;

	using net.ideaity.util.events;
	
	using org.nxbre.util;
	
	/// <summary>
	/// Driver for loading rules files valid against xBusinessRules.xsd (simplified NxBRE grammar).
	/// The native NxBRE rules file will be generated by XSLT.
	/// </summary>
	/// <author>David Dossot</author>
	/// <remarks>
	///  xBusinessRules.xsd, transformXRules.xsl and businessRules.xsd must be included in the assembly.
	/// </remarks>
	public class XBusinessRulesFileDriver:XSLTRulesFileDriver {
		
		public XBusinessRulesFileDriver(string xmlFileURI):base(xmlFileURI) {
			if (LogDispatcher != null)
				LogDispatcher.DispatchLog("XBusinessRulesFileDriver accessing "+Parameter.GetString("transformxrules.xsl", "transformXRules.xsl")+" in assembly",
				                          LogEventImpl.INFO);
			
			inputXMLSchema = Parameter.GetString("xbusinessrules.xsd", "xBusinessRules.xsd");
			
			xslt = new XslTransform();
			xslt.Load(new XmlTextReader(Assembly
			                            .GetExecutingAssembly()
			                            .GetManifestResourceStream(Parameter.GetString("transformxrules.xsl", "transformXRules.xsl"))), null, null);
		}
	}
}
