//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
//
// This source code was updated by David Dossot.
// 
namespace NxBRE.InferenceEngine.Registry.Configuration {
  using System.Xml.Serialization;
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class FileRegistryConfiguration {
      
    private Engine[] engineField;
    
    private string folderField;
    
    private int fileLockedPonderatingTimeField;
    
    public FileRegistryConfiguration() {
        this.fileLockedPonderatingTimeField = 500;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Engine")]
    public Engine[] Engines {
        get {
            return this.engineField;
        }
        set {
            this.engineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Folder {
        get {
            return this.folderField;
        }
        set {
            this.folderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="int")]
    [System.ComponentModel.DefaultValueAttribute(500)]
    public int FileLockedPonderatingTime {
        get {
            return this.fileLockedPonderatingTimeField;
        }
        set {
            this.fileLockedPonderatingTimeField = value;
        }
    }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class Engine {
      
      private Rules rulesField;
      
      private object binderField;
      
      private string idField;
      
      /// <remarks/>
      public Rules Rules {
          get {
              return this.rulesField;
          }
          set {
              this.rulesField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlElementAttribute("CSharpBinder", typeof(CSharpBinder))]
      [System.Xml.Serialization.XmlElementAttribute("FlowEngineBinder", typeof(FlowEngineBinder))]
      public object Binder {
          get {
              return this.binderField;
          }
          set {
              this.binderField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
      public string id {
          get {
              return this.idField;
          }
          set {
              this.idField = value;
          }
      }
  }
    
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class Rules {
      
      private string fileField;
      
      private RulesFormat formatField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string file {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public RulesFormat format {
          get {
              return this.formatField;
          }
          set {
              this.formatField = value;
          }
      }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  public enum RulesFormat {
      
      /// <remarks/>
      HRF086,
      
      /// <remarks/>
      RuleML08Datalog,
      
      /// <remarks/>
      RuleML086Datalog,
      
      /// <remarks/>
      RuleML086NafDatalog,
      
      /// <remarks/>
      RuleML09NafDatalog,
      
      /// <remarks/>
      Visio2003,
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class CSharpBinder {
      
      private string fileField;
      
      private string classField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string file {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string @class {
          get {
              return this.classField;
          }
          set {
              this.classField = value;
          }
      }
  }
  
  /// <remarks/>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
  [System.SerializableAttribute()]
  [System.Diagnostics.DebuggerStepThroughAttribute()]
  [System.ComponentModel.DesignerCategoryAttribute("code")]
  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
  [System.Xml.Serialization.XmlRootAttribute(Namespace="http://nxbre.org/registry/file", IsNullable=false)]
  public partial class FlowEngineBinder {
      
      private string fileField;
      
      private NxBRE.InferenceEngine.IO.BindingTypes typeField;
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public string file {
          get {
              return this.fileField;
          }
          set {
              this.fileField = value;
          }
      }
      
      /// <remarks/>
      [System.Xml.Serialization.XmlAttributeAttribute()]
      public NxBRE.InferenceEngine.IO.BindingTypes type {
          get {
              return this.typeField;
          }
          set {
              this.typeField = value;
          }
      }
  }
  
//  /// <remarks/>
//  [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
//  [System.SerializableAttribute()]
//  [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
//  public enum FlowEngineBinderType {
//      
//      /// <remarks/>
//      BeforeAfter,
//      
//      /// <remarks/>
//      Control,
//  }
  
}
